#[cfg(feature = "ssr")]
pub mod config;
#[cfg(feature = "ssr")]
pub mod db;
#[cfg(feature = "ssr")]
pub mod auth;
#[cfg(feature = "ssr")]
pub mod websocket;
#[cfg(feature = "ssr")]
pub mod schema;
#[cfg(feature = "ssr")]
pub mod models;

pub mod category;
pub mod event;
pub mod item;
pub mod order;
pub mod product;
pub mod settings;
pub mod station;
pub mod user;
